title:              Clean Blog
email:              rudals20060@gmail.com
description:        A Blog Theme by Start Bootstrap
author:             Start Bootstrap
baseurl:            "/"
url:                "https://dbrudals922.github.io"

# Social Profiles
twitter_username:
github_username:    dbrudals922
facebook_username:  
instagram_username:  min__9221
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
